### ISSUE TITLE
Unable to execute pseudo successfully on non-admin user

### ISSUE THREAD

**Issue by sidbena** [sstephenson/pseudo#1]
I'm experiencing an issue when executing `pseudo` on my machines.
If the executing user is not an admin account, `pseudo` seems to fail. It triggers the authentication prompt correctly, but despite entering correct credentials, `pseudo` exits with a non-zero exit code. Executing the exact same code on an admin account generates no error.
That is:
`./pseudo -m "Test" && echo "Success" || echo "Fail"`
always results in `Fail` on non-admin accounts.

**Comment by sstephenson** [comment]
You’ll need to edit `/etc/sudoers` to grant sudo privileges to non-admin users. See `man 5 sudoers` for details.

**Comment by sidbena** [comment]
Ah, I'm not sure I was clear enough. The authentication prompt is getting filled with an admin users credentials, I'm not trying to authenticate as the non-admin user (which I guess the security framework in OS X wouldn't accept as correct credentials anyway). Or perhaps you already understood that, in which case I'm unfortunately unsure on what to do with the information you gave me. If I can't elevate with pseudo, I can't really make any edits to /etc/sudoers anyway. Having to do this prior to executing the script would require some code to find an admin account and then change user to that account prior to executing pseudo, which seems like a lot of work.

**Comment by sstephenson** [comment]
Pseudo is just calling `sudo` under the hood. I think you’ll find you’re not able to run `sudo` from a non-admin account, either. If you want that to work, you’ll have to edit `/etc/sudoers` (as root) to enable non-admin access.

**Comment by sidbena** [comment]
Hello again!
There's no way to make pseudo execute its privilege escalation as the user who's actually authenticating to the security framework of OS X, then? I guess not, but I'd be neat.

**Comment by sstephenson** [comment]
Yeah, that’s correct. Sorry.
